//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int IdCar { get; set; }
        public string CarBrand { get; set; }
        public string CarModel { get; set; }
        public Nullable<short> ReleaseYear { get; set; }
        public string TransmissionType { get; set; }
        public Nullable<short> EnginePower { get; set; }
        public int PersonId { get; set; }
    
        public virtual Person Persons { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
