//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class car_serviceEntities : DbContext
    {
        public car_serviceEntities()
            : base("name=car_serviceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> CarSet { get; set; }
        public DbSet<Operation> OperationSet { get; set; }
        public DbSet<Order> OrderSet { get; set; }
        public DbSet<Person> PersonSet { get; set; }
    }
}
